package:
    name: gridutils
    version: 1.0

source:
    git_url: https://github.com/sakov/gridutils-c.git
    git_tag: v1.0

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - nn
        - csa
    run:
        - nn
        - csa
        - libgcc

test:
    commands:
        - gridbathy -h

about:
    home: https://github.com/sakov/gridutils-c
    license: Simplified BSD
    summary: C library functions and command line utilities for working with curvilinear grids.

extra:
    recipe-maintainers:
        - ocefpaf
